# Extended config for DEVELOPMENT env
version: "3.7"
services:
  backend:
    volumes:
      - "${PWD}/api/src:/home/node/app/src"
    command: yarn start

  frontend:
    build:
      target: base
    volumes:
      - "${PWD}/frontend:/app"
      - node_modules:/app/node_modules
    ports:
      - "5080:8080"
    environment:
      - API=http://backend:5050
    command: yarn start

  triplestore:
    volumes:
      - "${PWD}/triplestore/drop:/root/graphdb-import"

volumes:
  node_modules:
