version: '3.7'
services:
  backend:
    image: wallscope/pronto-backend:1.1.1
    build: 'api/'
    ports:
      - '5050:5050'
    environment:
      - TRIPLESTORE=http://triplestore:7200/repositories/ontologySearcher
    networks:
      - pronto-net

  frontend:
    image: wallscope/pronto-frontend:1.0.1
    build:
      context: frontend/
    networks:
      - pronto-net

  triplestore:
    image: dhlabbasel/graphdb-free
    ports:
      - '127.0.0.1:5070:7200'
    volumes:
      - '${PWD}/triplestore/drop:/root/graphdb-import'
      - '${PWD}/triplestore/data:/graphdb/data'
    networks:
      - pronto-net

networks:
  pronto-net:
