version: "3.7"
services:
  backend:
    build: "backend/"
    ports:
      - "5050:5050"
    restart: always
    networks:
      - pronto-net

  frontend:
    build:
      context: frontend/
    restart: always
    networks:
      - pronto-net

networks:
  pronto-net:
