# Extended config for PRODUCTION env
version: "3"
services:
  backend:
    image: docker.pkg.github.com/wallscope/pronto/backend:2.0.0
    ports:
      - "5050:5050"
    logging:
      driver: awslogs
      options:
        awslogs-group: pronto
        awslogs-region: eu-west-1
        awslogs-stream-prefix: backend

  frontend:
    image: docker.pkg.github.com/wallscope/pronto/frontend:2.0.0
    ports:
      - "80:80"
    volumes:
      - "/etc/nginx/conf.d"
    depends_on:
      - backend
    logging:
      driver: awslogs
      options:
        awslogs-group: pronto
        awslogs-region: eu-west-1
        awslogs-stream-prefix: frontend
