apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  # labels:
  #   service: pronto-frontend
  name: pronto-frontend
spec:
  selector:
    matchLabels:
      app: pronto-frontend
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      creationTimestamp: null
      labels:
        pronto-net: 'true'
        app: pronto-frontend
    spec:
      containers:
        - image: docker.pkg.github.com/wallscope/pronto/frontend:1.0.2
          imagePullPolicy: IfNotPresent
          name: pronto-frontend
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 80
          env:
            - name: BACKEND
              value: http://pronto-backend
      restartPolicy: Always
