apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    service: pronto-triplestore-claim0
  name: pronto-triplestore-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3000Mi
