apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: pronto
    tier: triplestore
  name: pronto-triplestore-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3000Mi
