apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pronto
    tier: triplestore
  name: pronto-triplestore
spec:
  selector:
    matchLabels:
      app: pronto
      tier: triplestore
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      creationTimestamp: null
      labels:
        pronto-net: "true"
        app: pronto
        tier: triplestore
    spec:
      containers:
        - image: dhlabbasel/graphdb-free
          imagePullPolicy: Always
          name: pronto-triplestore
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "300m"
          # volumeMounts:
          #   - mountPath: /graphdb/data
          #     name: triplestore-claim0
      restartPolicy: Always
      # volumes:
      #   - name: triplestore-claim0
      #     persistentVolumeClaim:
      #       claimName: pronto-triplestore-claim0
